protobuf is required for all (Apple Silicon & intel clip as well)
https://substrate.stackexchange.com/questions/4015/failed-to-run-custom-build-command-for-libp2p-core-v0-34-0

error: failed to run custom build command for `libp2p-core v0.38.0`

Caused by:
  process didn't exit successfully: `/Users/adibir/Desktop/Impactility/substrate-node-template/target/release/build/libp2p-core-af21bf2b03805b28/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.You could try running `brew install protobuf` or downloading it from https://github.com/protocolbuffers/protobuf/releases

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /Users/adibir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-0.11.9/src/lib.rs:1457:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...